# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot = {
    loader.systemd-boot.enable = true;
    loader.efi.canTouchEfiVariables = true;
    initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "sd_mod" ];
    kernelModules = [ "kvm-intel" ];
    blacklistedKernelModules = [ "dvb_usb_rtl28xxu" "rtl2832" "rtl2838" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-id/ata-Samsung_SSD_850_EVO_500GB_S21HNXAG451663B-part2";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-id/ata-Samsung_SSD_850_EVO_500GB_S21HNXAG451663B-part1";
      fsType = "vfat";
    };

    "/srv/raid" = {
      label = "data";
      fsType = "ext4";
    };
  };

  hardware.bluetooth.enable = true;
  hardware.rtl-sdr.enable = true;

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 16;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

}
